### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by azrazalea** [dptd/derp#6]
Hello, i'm wanting to use derp and/or JASAW for my own use but I notice there is no license. Can you put it under an OSI approved license please?

Thank you!

**Comment by dptd** [comment]
@azrazalea I have no idea why I didn't get any information that someone created issue here, sorry! Of course you can use it. The license is MIT.

Sorry for the late reply!

**Comment by dptd** [comment]
One more thing. Some time ago I divided `derp` package to `jasb` and `derp` to make it easier to create other, custom Slack bots. If you will have any issues with running `derp` please let me know.
